- hosts: all
  gather_facts: yes
  become: yes
  vars:
    NODEJS_VERSION: "10.x"
    ansible_distribution_release: "streth" #trusty
  tasks:
#    - name: Install apt-transport-https
#      apt:
#        name: apt-transport-https

#    - name: Install the gpg key for nodejs LTS
#      apt_key:
#        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
#        state: present

    - name: Install Curl
      apt:
        name: curl

    - name: Add node repo
      shell: curl -sL https://deb.nodesource.com/setup_{{ NODEJS_VERSION }} | bash -
    
    - name: apt update
      apt:
        update_cache: yes
 

#    - name: Install the nodejs LTS repos
#      apt_repository:
#        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
#        state: present
#        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
